### ISSUE TITLE
.sc should be the colorless mana symbol not the chaos

### ISSUE THREAD

**Issue by dafreaki** [micku/mana-cost#3]
.scl is used for colorless but c is used for colorless in the mtgjson

**Comment by micku** [comment]
In mtgjson {C} is used for Chaos Symbol too, as you can see here:
https://github.com/mtgjson/mtgjson/blob/3da45f3670c6e15eb340c8a68a4281f3f4ede0a3/json/PC2.json#L53
It's legit to revert the symbols since colorless, now, is more used, but this will break the compatiblity.

For now I'll keep it as is, let's see if someone else prefer to revert the symbols.

**Comment by dafreaki** [comment]
they are replacing the symbol https://github.com/mtgjson/mtgjson/issues/126
https://github.com/mtgjson/mtgjson/commit/e3176f80f0ff81219e2004d17be7459bbc3b75b0

**Comment by micku** [comment]
Thank you @dafreaki for finding it out! I'll fix it as soon as possible.
