### ISSUE TITLE
when using mana-cost and bootstrap small font size gets changes to 85%

### ISSUE THREAD

**Issue by dafreaki** [micku/mana-cost#5]
adding 

.mana.small{
    font-size: 100%;
}
 should override the bootstrap .small

i have also noticed that the font-size alters the size of the symbols i.e. font-size 14px will resize the symbol

**Comment by micku** [comment]
@dafreaki can you provide an example of the issue?

Anyway, it was somewhat intended to let the size be customizable, unfortunately I do not have the knowledge to say which is the right way.
Since you are using it with Bootstrap, can you do a pull request when you think this is actually working in the right way? I will be **SOOOOO** happy :)

**Comment by petermorgandev** [comment]
The conflict here is that bootstrap is also using `.small` to make text, well, smaller. Here is the bootstrap CSS:

```css
.small, small {
    font-size: 80%;
    font-weight: 400;
```

How could this be fixed?

One way would be to modify the CSS for this project to this:

```css
.mana.small {
    height: 1em;
    width: 1em;
    font-size: 100%;
}
```

The other would be to change the names of the classes related to size. Instead of `.small`, `.medium`, and `.large` the classes could be named `.mana-sm`, `.mana-md`, `.mana-lg`, or something to that effect. The potential downside is that changing the classes would break any project that links directly to the CSS on GitHub.
